version: '3.7'

services:
  test:
    extends:
      service: test
      file: docker-compose.yml
    command: npm run test
    build:
      context: ./api
      dockerfile: ./docker/test.dockerfile
    depends_on:
      - database
    restart: "no"
    image: ydb-orm:test
    environment:
      - NODE_ENV=test

  database:
    extends:
      service: database
      file: docker-compose.yml
    restart: "no"
    environment:
      - YDB_USE_IN_MEMORY_PDISKS=true

networks:
  local:
    driver: bridge

volumes:
  ydb_certs:

