services:
  database:
    extends:
      file: docker-compose.yaml
      service: database
    hostname: localhost
    ports:
      - 2136:2136
      - 8765:8765
    networks:
      - local

networks:
  local:
    driver: bridge
