import { nanoid } from 'nanoid'

import { YdbDataType, YdbModel, YdbSchemaType } from '../..'

type Fields = {
  id: string
  name: string
  createdAt: Date
}

export class User extends YdbModel implements Fields {
  static schema: YdbSchemaType = {
    id: YdbDataType.ascii,
    name: YdbDataType.ascii,
    createdAt: YdbDataType.date,
  }

  // can be autogenerated after `implements` use
  id: Fields['id']
  name: Fields['name']
  createdAt: Fields['createdAt']

  constructor(fields: Partial<Fields>) {
    super(fields)

    const { name, id, createdAt } = fields
    this.id = id || nanoid()
    this.name = name || ''
    this.createdAt = createdAt || new Date()
  }
}
