name: PR Node Built Docker

on:
  pull_request:

jobs:
  node-built-docker:
    name: Node Built Library Tests in Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d database
      - run: sleep 15
      - run: docker compose run --rm node-test
        env:
          NODE_DOCKER_PLATFORM: linux/amd64
      - if: always()
        run: docker compose down -v
