name: Test Node.js

on:
  pull_request:

jobs:
  run:
    name: test-nodejs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22, 24]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run docker:db-up
      - run: npm run test:nodejs
        env:
          YDB_ENDPOINT: grpc://localhost:2136
          YDB_DATABASE: /local
      - if: always()
        run: npm run docker:db-down
