name: Tests Cloud

on:
  pull_request:

jobs:
  run:
    name: test-cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14
      - name: install yc cli
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i "$HOME/.local/yc" -n
          echo "$HOME/.local/yc" >> "$GITHUB_PATH"
      - run: |
          jq -r '.' > ./sa-key.json << EOF
          ${{ secrets.YC_SA_KEY }}
          EOF
      - run: bun install --frozen-lockfile
      - run: bun run test:cloud
        env:
          YC_CLOUD_ID: ${{ vars.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ vars.YC_FOLDER_ID }}
