name: Test Docker

on:
  pull_request:

jobs:
  run:
    name: test-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14
      - run: bun run test:docker
      - if: always()
        run: bun run test:docker:clean
